# Generated by Django 4.2.6 on 2023-11-22 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('DL', 'Delhi'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal'), ('MH', 'Maharashtra'), ('RJ', 'Rajasthan'), ('MP', 'Madhya Pradesh'), ('TN', 'Tamil Nadu'), ('AP', 'Andhra Pradesh'), ('KA', 'Karnataka'), ('OR', 'Orissa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('PB', 'Punjab'), ('JH', 'Jharkhand'), ('HP', 'Himachal Pradesh'), ('UT', 'Uttarakhand'), ('UK', 'Uttrakhand'), ('AN', 'Andaman and Nicobar Islands'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('LD', 'Lakshadweep'), ('PY', 'Pondicherry'), ('SK', 'Sikkim'), ('JK', 'Jammu and Kashmir'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('MN', 'Manipur'), ('NL', 'Nagaland'), ('ML', 'Meghalaya')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
